# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy Lambda Functions

on:
  workflow_dispatch:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Package a lambda function
      uses: nickminaev/package-lambda-with-uv-action@26dfd41e55c8ee4cb65d8d6fd534b238d6eef39b
      with:
        working-directory: lambdas/src/tg_bot_authorizer


