name: Destroy Telegram Bot Infra

on:
  workflow_dispatch:

jobs:
    destroy:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: infra
      permissions:
          id-token: write
      steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Assume the role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.TG_BOT_DEPLOYER_ROLE_NAME }}
          role-session-name: deployLambdas
      - name: Terraform Init
        run: terraform init
      - name: Terraform destroy
        run: terraform destroy -auto-approve